name: AttendanceApp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  flutter_local_notifications: ^19.4.2
  provider: ^6.1.5+1
  encrypt: ^5.0.1
  share_plus:
  sqflite: ^2.4.2
  fl_chart: ^1.1.1
  crypto: ^3.0.6
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  local_auth: ^2.3.0
  syncfusion_flutter_charts: ^31.2.4
  sqlcipher_flutter_libs: ^0.6.8
  url_launcher: ^6.3.2
  file_saver: ^0.3.1
  csv:
  path_provider:
  path:
  intl:
  camera:
  image:
  image_picker:
  flutter_background_service:
  workmanager:
  http:
  geolocator:
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.4
  file_picker:
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/images/

  uses-material-design: true
